const Arr=[
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores labore assumenda sed iusto repellendus. Labore obcaecati fuga, distinctio maxime cupiditate officia nemo culpa commodi, totam voluptatibus optio accusamus deserunt necessitatibus hic veritatis tenetur consequuntur beatae inventore autem est aperiam quasi recusandae eaque! Itaque necessitatibus veniam nemo? Ratione tenetur sequi perferendis ducimus suscipit. Aliquid illum praesentium sunt hic fugiat consectetur error.",

    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ipsum ipsa id natus facere cupiditate, et veritatis! Soluta maxime quia accusamus doloribus cumque iste pariatur sit nisi totam. Dolore eaque ex magnam vero eveniet voluptatibus itaque placeat quod suscipit, perferendis repellat, illum maiores similique animi, magni laudantium mollitia aliquam facere natus. Esse officiis eius, aperiam ducimus atque vel dolorum unde magni inventore ipsum est ut minima? Quasi qui tempora explicabo illum iusto architecto, laboriosam reprehenderit corporis. Iure sapiente eius eum? Ipsa assumenda dolor pariatur est quae provident expedita eos totam, optio exercitationem dicta veritatis possimus sunt veniam id aliquam voluptatibus?" ,

    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis quod soluta aliquid, maiores temporibus dolorem, animi earum quasi itaque voluptas quidem dolores voluptate accusantium maxime perferendis et odio cum nemo fugiat enim libero rem magnam sed. Temporibus nulla labore ipsam voluptatum deleniti, eum perspiciatis doloremque incidunt voluptatibus quidem, possimus animi. Inventore soluta magnam esse assumenda incidunt! Minus asperiores a praesentium reiciendis officiis sapiente, minima esse necessitatibus magni optio inventore molestiae dolorum fugit delectus excepturi molestias aliquid ex veniam perspiciatis totam veritatis. Molestiae ducimus nulla dicta harum magni nemo veritatis aut! Excepturi, praesentium corrupti aliquid porro facilis quia enim. Nobis dignissimos quae dolores adipisci alias doloremque minus deleniti nam cum? Qui suscipit veritatis ab facere nam similique exercitationem fugit illum numquam." ,

    "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nihil, quidem id? Voluptatum tempore ipsum aut rerum magni, aperiam corrupti odio quasi quam quidem. Obcaecati numquam harum consequuntur, reprehenderit debitis cum dignissimos. Error repellendus veritatis quo asperiores sit labore obcaecati esse consequuntur dicta commodi, corporis dolor, illum corrupti consectetur nihil voluptatem molestiae molestias maiores minima ipsam nulla? Recusandae cupiditate vel quaerat alias corporis iusto quisquam nostrum consectetur laborum id hic molestias, vitae libero voluptate unde ratione sunt accusamus, ipsam, accusantium fuga animi iure quos provident in! Harum minus est optio voluptates!" ,

    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ullam debitis reiciendis temporibus id ut, adipisci recusandae unde ad distinctio exercitationem. Necessitatibus, sequi, quod odit amet fuga doloribus libero culpa iste reprehenderit nostrum dolor facere earum qui reiciendis quos officia. Accusamus doloribus maiores aperiam repellendus excepturi saepe? Libero, sequi beatae laborum veritatis esse labore ipsa facilis porro voluptatum delectus quas accusantium quasi repudiandae itaque explicabo voluptatem, nam quam! Fugit, perspiciatis accusamus. Nam similique officiis est, vero inventore deleniti nihil. Unde suscipit dolores facilis deserunt dolore fugit ratione facere voluptas, neque hic nobis nam! Ipsam odio ea ipsa dignissimos nihil quo eos. Tempora perferendis modi quam. Architecto maxime doloremque quis illum assumenda?" ,

    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae dignissimos, voluptas deserunt odio reiciendis nobis vero delectus numquam similique mollitia dolore minima, alias eligendi veniam assumenda repellendus expedita aspernatur? Cum cumque debitis a ipsum porro quod deserunt error quos delectus perspiciatis soluta, optio tenetur consequatur, pariatur, nisi officia assumenda accusamus.' ,

    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo amet, placeat asperiores vitae temporibus repellendus in laboriosam quam eos maiores facilis ab nisi labore hic doloremque quia voluptatum nostrum accusamus, aut, officia odio. A esse iusto eveniet, minus sed labore deserunt et vero ex ipsum, voluptatum voluptate aliquam provident dignissimos distinctio minima. Fuga, quisquam! Animi eum minus aliquid odio facilis!" ,

    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo quasi iste deleniti minus voluptatem ea beatae nesciunt? Ullam, nisi quidem dolorem qui voluptatem dolorum velit quod inventore corrupti eligendi sint veritatis illum architecto fuga magnam suscipit pariatur optio aliquid earum dolor sapiente eum! Dolorem, corrupti, minima consequuntur aliquam culpa, voluptas laudantium neque non temporibus ab corporis omnis. Deleniti eum suscipit molestias et est ab eius necessitatibus dicta, delectus illo omnis!" ,

    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Assumenda voluptatem atque rem itaque repellendus magnam fugiat exercitationem, deleniti aliquid officia quasi commodi tempore numquam in, error pariatur nesciunt maiores tempora molestiae explicabo eos odio! Cupiditate deleniti earum distinctio nostrum esse?" ,

    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio id quam eaque. Minus inventore laborum libero nam placeat. Libero, eum vel! Ullam dolorum ipsa tempore enim voluptatum iste ab praesentium?" ,

    "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae quasi minima asperiores vitae? Omnis fugiat hic corrupti quo odit maxime obcaecati, labore laborum dolorem mollitia minus, dolorum eligendi quidem provident." ,
]

export default Arr;